"""Object storage abstraction: local disk (development) or Amazon S3 / MinIO (cloud).

Keys are always generated by the backend and validated; the database stores
only keys and metadata, never video bytes. Access to objects is granted with
short-lived signed URLs (HMAC for local, presigned URLs for S3).
"""
from __future__ import annotations

import hashlib
import logging
import re
import shutil
import time
from datetime import datetime
from pathlib import Path
from urllib.parse import quote, urlencode

from ..core.config import get_settings
from ..core.security import sign_media

log = logging.getLogger("vms.storage")

_KEY_RE = re.compile(r"^(recordings|evidence|snapshots|thumbnails|exports)/[A-Za-z0-9_\-./]+$")


class InvalidKey(ValueError):
    pass


def validate_key(key: str) -> str:
    if not _KEY_RE.match(key) or ".." in key.split("/") or "//" in key or key.endswith("/"):
        raise InvalidKey(f"invalid storage key: {key!r}")
    return key


# ------------------------------------------------------------------ key builders
def recording_key(camera_id: int, start: datetime, segment_name: str) -> str:
    return validate_key(f"recordings/{camera_id}/{start:%Y-%m-%d}/{segment_name}")


def evidence_key(camera_id: int, ts: datetime, event_id: int, ext: str = "mp4") -> str:
    return validate_key(f"evidence/{camera_id}/{ts:%Y-%m-%d}/{event_id}/clip.{ext}")


def snapshot_key(camera_id: int, ts: datetime, event_id: int) -> str:
    return validate_key(f"snapshots/{camera_id}/{ts:%Y-%m-%d}/{event_id}/snapshot.jpg")


def thumbnail_key(camera_id: int) -> str:
    return validate_key(f"thumbnails/{camera_id}/latest.jpg")


class UploadTooLarge(ValueError):
    pass


def save_upload(src, dst: Path, max_mb: int) -> int:
    """Stream an uploaded file to ``dst``, refusing (and removing) anything larger than ``max_mb``."""
    limit, size = max_mb * 1024 * 1024, 0
    try:
        with open(dst, "wb") as f:
            for chunk in iter(lambda: src.read(1 << 20), b""):
                size += len(chunk)
                if size > limit:
                    raise UploadTooLarge(f"File is larger than the {max_mb} MB limit")
                f.write(chunk)
    except BaseException:
        dst.unlink(missing_ok=True)
        raise
    return size


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


class Storage:
    backend = "base"

    def put_file(self, key: str, path: Path, content_type: str, move: bool = False) -> int: ...
    def put_bytes(self, key: str, data: bytes, content_type: str) -> int: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def signed_url(self, key: str, ttl: int | None = None) -> str: ...
    def local_path(self, key: str) -> Path | None:
        return None
    def usage_bytes(self) -> int:
        return 0

    def put_file_with_retry(self, key: str, path: Path, content_type: str, move: bool = False,
                            attempts: int = 3) -> tuple[int, int]:
        """Returns (size, attempts_used). Raises the last error if every attempt fails."""
        last: Exception | None = None
        for i in range(1, attempts + 1):
            try:
                return self.put_file(key, path, content_type, move=move), i
            except Exception as exc:  # network / permission errors
                last = exc
                log.warning("upload of %s failed (attempt %d/%d): %s", key, i, attempts, exc)
                time.sleep(min(2 ** i, 10))
        assert last is not None
        raise last


class LocalStorage(Storage):
    backend = "local"

    def __init__(self, root: Path):
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        p = (self.root / validate_key(key)).resolve()
        if self.root.resolve() not in p.parents:
            raise InvalidKey(key)
        return p

    def put_file(self, key, path, content_type, move=False):
        dst = self._path(key)
        dst.parent.mkdir(parents=True, exist_ok=True)
        if move:
            shutil.move(str(path), dst)
        else:
            shutil.copyfile(path, dst)
        return dst.stat().st_size

    def put_bytes(self, key, data, content_type):
        dst = self._path(key)
        dst.parent.mkdir(parents=True, exist_ok=True)
        tmp = dst.with_suffix(dst.suffix + ".part")
        tmp.write_bytes(data)
        tmp.replace(dst)  # atomic, readers never see half a file
        return len(data)

    def delete(self, key):
        p = self._path(key)
        if p.exists():
            p.unlink()

    def exists(self, key):
        return self._path(key).exists()

    def local_path(self, key):
        return self._path(key)

    def signed_url(self, key, ttl=None):
        validate_key(key)
        exp = int(time.time()) + (ttl or get_settings().media_url_ttl_seconds)
        return f"/api/media/{quote(key)}?" + urlencode({"exp": exp, "sig": sign_media(key, exp)})

    def usage_bytes(self):
        return sum(f.stat().st_size for f in self.root.rglob("*") if f.is_file())


class S3Storage(Storage):
    backend = "s3"

    def __init__(self, bucket: str, region: str, endpoint_url: str = "", prefix: str = ""):
        import boto3
        from botocore.config import Config
        self.bucket, self.prefix = bucket, prefix.strip("/")
        self.client = boto3.client(
            "s3", region_name=region, endpoint_url=endpoint_url or None,
            config=Config(retries={"max_attempts": 5, "mode": "standard"}, signature_version="s3v4"))

    def _k(self, key: str) -> str:
        validate_key(key)
        return f"{self.prefix}/{key}" if self.prefix else key

    def put_file(self, key, path, content_type, move=False):
        self.client.upload_file(str(path), self.bucket, self._k(key),
                                ExtraArgs={"ContentType": content_type, "ServerSideEncryption": "AES256"})
        size = Path(path).stat().st_size
        if move:
            Path(path).unlink(missing_ok=True)
        return size

    def put_bytes(self, key, data, content_type):
        self.client.put_object(Bucket=self.bucket, Key=self._k(key), Body=data,
                               ContentType=content_type, ServerSideEncryption="AES256")
        return len(data)

    def delete(self, key):
        self.client.delete_object(Bucket=self.bucket, Key=self._k(key))

    def exists(self, key):
        try:
            self.client.head_object(Bucket=self.bucket, Key=self._k(key))
            return True
        except Exception:
            return False

    def signed_url(self, key, ttl=None):
        return self.client.generate_presigned_url(
            "get_object", Params={"Bucket": self.bucket, "Key": self._k(key)},
            ExpiresIn=ttl or get_settings().media_url_ttl_seconds)

    def usage_bytes(self):
        total = 0
        paginator = self.client.get_paginator("list_objects_v2")
        for page in paginator.paginate(Bucket=self.bucket, Prefix=self.prefix or ""):
            total += sum(o["Size"] for o in page.get("Contents", []))
        return total


_storage: Storage | None = None


def get_storage() -> Storage:
    global _storage
    if _storage is None:
        s = get_settings()
        if s.storage_backend == "s3":
            if not s.s3_bucket:
                raise RuntimeError("VMS_S3_BUCKET must be set when VMS_STORAGE_BACKEND=s3")
            _storage = S3Storage(s.s3_bucket, s.s3_region, s.s3_endpoint_url, s.s3_prefix)
        else:
            _storage = LocalStorage(s.storage_dir)
    return _storage


def set_storage(storage: Storage | None) -> None:  # used by tests
    global _storage
    _storage = storage
